kafka:
  consumer:
    properties:
      auto.offset.reset: "earliest"
      bootstrap.servers: "localhost:9092"
      client.id: "consumer-exactly-once-processing"
      enable.auto.commit: false
      group.id: "consumer-exactly-once-processing"
      isolation.level: "read_committed"
      key.deserializer: "org.apache.kafka.common.serialization.StringDeserializer"
      schema.registry.url: "http://localhost:8081"
      specific.avro.reader: true
      value.deserializer: "io.confluent.kafka.serializers.KafkaAvroDeserializer"
  producer:
    properties:
      avro.remove.java.properties: true
      bootstrap.servers: "localhost:9092"
      client.id: "producer-exactly-once-processing"
      key.serializer: "org.apache.kafka.common.serialization.StringSerializer"
      schema.registry.url: "http://localhost:8081"
      transactional.id: "producer-exactly-once-processing"
      value.serializer: "io.confluent.kafka.serializers.KafkaAvroSerializer"
