kafka:
  properties:
    application.id: "streams-exception-handler-processing-papi"
    avro.remove.java.properties: true
    bootstrap.servers: "localhost:9092"
    client.id: "streams-exception-handler-processing-papi"
    processing.exception.handler: "io.github.loicgreffier.streams.exception.handler.processing.papi.error.CustomProcessingExceptionHandler"
    replication.factor: 1
    schema.registry.url: "http://localhost:8081"
    state.dir: "/tmp/kafka-streams-quickstarts"
