kafka:
  properties:
    acks: "all"
    application.id: "streams-processing-exception-handler-papi"
    auto.offset.reset: "earliest"
    avro.remove.java.properties: true
    bootstrap.servers: "localhost:9092"
    client.id: "streams-processing-exception-handler-papi"
    min.insync.replicas: 1
    num.stream.threads: 1
    processing.exception.handler: "io.github.loicgreffier.streams.exception.handler.processing.papi.error.CustomProcessingExceptionHandler"
    replication.factor: 1
    schema.registry.url: "http://localhost:8081"
    state.dir: "/tmp/kafka-streams-quickstarts"
