kafka:
  properties:
    bootstrap.servers: localhost:9092
    schema.registry.url: http://localhost:8081
    application.id: streams-left-join-stream-global-table
    client.id: streams-left-join-stream-global-table
    state.dir: /tmp/kafka-streams-quickstarts
    acks: all
    auto.offset.reset: earliest
    avro.remove.java.properties: true