kafka:
  properties:
    application.id: "streams-exception-handler-deserialization"
    avro.remove.java.properties: true
    bootstrap.servers: "localhost:9092"
    client.id: "streams-exception-handler-deserialization"
    deserialization.exception.handler: "io.github.loicgreffier.streams.exception.handler.deserialization.error.CustomDeserializationExceptionHandler"
    replication.factor: 1
    schema.registry.url: "http://localhost:8081"
    state.dir: "/tmp/kafka-streams-quickstarts"
