kafka:
  properties:
    acks: "all"
    application.id: "streams-deserialization-exception-handler"
    auto.offset.reset: "earliest"
    avro.remove.java.properties: true
    bootstrap.servers: "localhost:9092"
    client.id: "streams-deserialization-exception-handler"
    deserialization.exception.handler: "io.github.loicgreffier.streams.exception.handler.deserialization.error.CustomDeserializationExceptionHandler"
    min.insync.replicas: 1
    num.stream.threads: 1
    replication.factor: 1
    schema.registry.url: "http://localhost:8081"
    state.dir: "/tmp/kafka-streams-quickstarts"
