kafka:
  properties:
    bootstrap.servers: "localhost:9092"
    client.id: "producer-simple"
    key.serializer: "org.apache.kafka.common.serialization.StringSerializer"
    value.serializer: "org.apache.kafka.common.serialization.StringSerializer"
