kafka:
  properties:
    bootstrap.servers: localhost:9092
    schema.registry.url: http://localhost:8081
    application.id: streams-processing-exception-handler
    client.id: streams-processing-exception-handler
    state.dir: /tmp/kafka-streams-quickstarts
    acks: all
    auto.offset.reset: earliest
    avro.remove.java.properties: true
    replication.factor: 1 # Consider setting to 3 in production
    min.insync.replicas: 1 # Consider setting to 2 (replication.factor - 1) in production
    num.stream.threads: 1
    processing.exception.handler: io.github.loicgreffier.streams.exception.handler.processing.error.CustomProcessingExceptionHandler