kafka:
  properties:
    application.id: "streams-exception-handler-dlq"
    avro.remove.java.properties: true
    bootstrap.servers: "localhost:9092"
    client.id: "streams-exception-handler-dlq"
    deserialization.exception.handler: "org.apache.kafka.streams.errors.LogAndContinueExceptionHandler"
    errors.dead.letter.queue.topic.name: "DLQ_TOPIC"
    processing.exception.handler: "org.apache.kafka.streams.errors.LogAndContinueProcessingExceptionHandler"
    production.exception.handler: "org.apache.kafka.streams.errors.DefaultProductionExceptionHandler"
    replication.factor: 1
    schema.registry.url: "http://localhost:8081"
    state.dir: "/tmp/kafka-streams-quickstarts"
