kafka:
  properties:
    auto.offset.reset: "earliest"
    bootstrap.servers: "localhost:9092"
    client.id: "consumer-avro-generic"
    enable.auto.commit: false
    group.id: "consumer-avro-generic"
    key.deserializer: "org.apache.kafka.common.serialization.StringDeserializer"
    schema.registry.url: "http://localhost:8081"
    value.deserializer: "io.confluent.kafka.serializers.KafkaAvroDeserializer"
