kafka:
  properties:
    bootstrap.servers: localhost:9092
    key.serializer: org.apache.kafka.common.serialization.StringSerializer
    value.serializer: org.apache.kafka.common.serialization.StringSerializer
    acks: all
    enable.idempotence: true
    max.in.flight.requests.per.connection: 5
    transactional.id: producer-transactional