{
  "namespace": "io.github.loicgreffier.avro",
  "type": "record",
  "name": "Customer",
  "fields": [
    {
      "name": "id",
      "type": [
        "null",
        "long"
      ],
      "default": null,
      "doc": "Customer id"
    },
    {
      "name": "firstName",
      "type": [
        "null",
        "string"
      ],
      "default": null,
      "doc": "Customer first name"
    },
    {
      "name": "lastName",
      "type": [
        "null",
        "string"
      ],
      "default": null,
      "doc": "Customer last name"
    },
    {
      "name": "email",
      "type": [
        "null",
        "string"
      ],
      "default": null,
      "doc": "Customer email"
    }
  ]
}
