kafka:
  properties:
    application.id: "streams-map"
    avro.remove.java.properties: true
    bootstrap.servers: "localhost:9092"
    client.id: "streams-map"
    replication.factor: 1
    schema.registry.url: "http://localhost:8081"
    state.dir: "/tmp/kafka-streams-quickstarts"
