kafka:
  properties:
    bootstrap.servers: localhost:9092
    schema.registry.url: http://localhost:8081
    application.id: streams-print
    client.id: streams-print
    state.dir: /tmp/kafka-streams-quickstarts
    acks: all
    auto.offset.reset: earliest
    avro.remove.java.properties: true

application:
  filePath: /tmp/kafka-streams-quickstarts/streams-print/streams-print-output.log