application:
  filePath: "/tmp/kafka-streams-quickstarts/streams-print/streams-print-output.log"
kafka:
  properties:
    application.id: "streams-print"
    avro.remove.java.properties: true
    bootstrap.servers: "localhost:9092"
    client.id: "streams-print"
    replication.factor: 1
    schema.registry.url: "http://localhost:8081"
    state.dir: "/tmp/kafka-streams-quickstarts"
