kafka:
  properties:
    acks: "all"
    avro.remove.java.properties: true
    bootstrap.servers: "localhost:9092"
    client.id: "producer-avro-specific"
    enable.idempotence: true
    key.serializer: "org.apache.kafka.common.serialization.StringSerializer"
    schema.registry.url: "http://localhost:8081"
    value.serializer: "io.confluent.kafka.serializers.KafkaAvroSerializer"
